# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"OprtType": "00_core.ipynb",
         "conv_unit": "00_core.ipynb",
         "relu_conv_bn": "00_core.ipynb",
         "conv_bn_relu": "00_core.ipynb",
         "bn_relu_conv": "00_core.ipynb",
         "relu_conv": "00_core.ipynb",
         "conv_bn": "00_core.ipynb",
         "resnet_basicblock": "00_core.ipynb",
         "resnet_bottleneck": "00_core.ipynb",
         "xception": "00_core.ipynb",
         "IdentityMapping": "00_core.ipynb",
         "Classifier": "00_core.ipynb",
         "init_cnn": "00_core.ipynb",
         "num_params": "00_core.ipynb",
         "cfg": "01_config.ipynb",
         "resnet_dag": "02_graph.ipynb"}

modules = ["core.py",
           "config.py",
           "graph.py",
           "network.py"]

git_url = "https://github.com/keepsimpler/wong/tree/master/"


def custom_doc_links(name): return None
