#AUTOGENERATED! DO NOT EDIT! File to edit: dev/01_config.ipynb (unless otherwise specified).

__all__ = ['assert_cfg', 'cfg']

#Cell
from .imports import *

#Cell
from yacs.config import CfgNode as CN

#Cell
_C = CN()

#Cell
_C.GRAPH = CN()

#Cell
_C.GRAPH.NUM_STAGES = 4
_C.GRAPH.NUM_NODES = (3, 8, 36, 3)
_C.GRAPH.NUM_CHANNELS = (64, 128, 256, 512)

#Cell
def assert_cfg(cfg):
    "Assert config options"
    assert cfg.GRAPH.NUM_STAGES == len(cfg.GRAPH.NUM_NODES), 'num_stages should equal to length of num_nodes'

#Cell
cfg = _C
